services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cleanapi-sql
    environment:
      SA_PASSWORD: "Strong@Horse9"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Strong@Horse9" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
  api:
    image: gangzdev/cleanapi-api:1.0
    container_name: cleanapi-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: "Server=sql;Database=CleanApiDb;User Id=sa;Password=Strong@Horse9;TrustServerCertificate=True;"
    depends_on:
      sql:
        condition: service_healthy
